### ISSUE TITLE
Google Analytics exclusivo

### ISSUE THREAD

**Issue by fititnt** [pokemongovet/casos-de-sucesso-na-adocao-de-animais#10]
O ID atual do projeto está usando a subconta "Pokemon Go" que é a de produção do site principal. Este issue é para dividir isto
### Tarefas
- [x] Criar subconta específica
- [x] Dar acesso a pessoas chave deste repositório
- [x] Implementar novo ID no código

**Comment by fititnt** [comment]
A @anabastos está com acesso em todas as contas do pokemongovet. Se mais alguém quiser acesso, avise.

**Comment by fititnt** [comment]
Pessoal, o novo UID é **UA-81144117-3**, quem puder faz o commit.

**Comment by evansantos** [comment]
Oi, eu pego lá 💃

**Comment by evansantos** [comment]
Atualizado no commit https://github.com/pokemongovet/casos-de-sucesso-na-adocao-de-animais/commit/e7a1f364a1b3186362cf111afe1181a1dc91be9c

**Comment by evansantos** [comment]
Posso fechar essa issue?

**Comment by fititnt** [comment]
@evansantos pode
