### ISSUE TITLE
Propósito desde repositório: listar notícias de casos de sucesso que fomentam adoção de animais

### ISSUE THREAD

**Issue by rcgivisiez** [pokemongovet/casos-de-sucesso-na-adocao-de-animais#2]
O objetivo desse repositório é listar notícias de casos de sucesso e, sempre que possível, saber mais informações, de modo a servir de inspiração para ações que vão além de apenas desenvolvimento de software.

Veja também https://github.com/pokemongovet/pokemongo.vet.br/issues/48

(TODO: continuar explicação)

**Comment by anabastos** [comment]
Para descrição mais detalhada do proposito deste repositorio, leiam o arquivo README.md dele.
