### ISSUE TITLE
Criar subdomínio dedicado para este repositório

### ISSUE THREAD

**Issue by anabastos** [pokemongovet/casos-de-sucesso-na-adocao-de-animais#3]
Neste momento, o site é servido pela URL https://pokemongovet.github.io/casos-de-sucesso-na-adocao-de-animais/. O ideal, na falta de ter um domínio próprio, é pelo menos ter um subdomínio.

Uma possibilidade seria http://casos-de-sucesso-na-adocao-de-animais.pokemongo.vet.br, mas isto pode ser grande.

Isso é meio urgente, logo talvez o domínio que for criado agora ainda pode ser alterado.
# Tarefas
- [x] Decidir nome do subdominio (mesmo que profisório) 
- [x] Apontar DNS para github pages
- [x] Criar CNAME com o respectivo subdominio
- [x] apontar outros links do repositório para novo dominio (caso seja necesário)

**Comment by fititnt** [comment]
Por enquanto eu tenho acesso ao registro.br do dominio principal. Vou passar acesso também pra pelo menos a @rcgivisiez . Quando tiver mais pessoas de infra na organização, posso deixar pra mais gente acesso de edição nas entradas DNS

Pode deixar pra mim o "Apontar DNS para o github pages" porém fico no aguardo de decidirem o que devo apontar, qual subdominio

**Comment by anabastos** [comment]
@fititnt Ainda precisamos decidir qual nome colocar. Tem alguem que sabe criar o CNAME e, se for necessario, alterar os links no Jekyll? Se sim, avisem aqui pra eu ja marcar isso como em andamento.

**Comment by evansantos** [comment]
@anabastos @fititnt eu assumo o CNAME e rever se os links estão ok, fico no aguardo dos outros decidirem

**Comment by fititnt** [comment]
Alguns nomes que pensei aqui
- ideiasquederamcerto.pokemongo.vet.br
- ideiasdesucesso.pokemongo.vet.br
- inove.pokemongo.vet.br

**Comment by fititnt** [comment]
Pronto. Agora a @rcgivisiez também tem poder total lá no domínio. Tinha ficado de fazer isso antes mas tinha esquecido. A @icoffani não sei se já tem UID no registro.br pra passar pra ela também.

**Comment by rcgivisiez** [comment]
Oi pessoal. Eu sugiro que o nome seja **Casos de Sucesso**.
Acho bem claro e explicativo.

**Comment by icoffani** [comment]
Conversei com a @rcgivisiez e o @fititnt e provavelmente será mesmo "**Casos de Sucesso**". Como a Renata disse, é claro, autoexplicativo, também é o nome que já usamos no canal de chat e uma versão resumida do nome do nosso repositório.

**Comment by fititnt** [comment]
```
casosdesucesso.pokemongo.vet.br A   192.30.252.153
casosdesucesso.pokemongo.vet.br A   192.30.252.154
```

DNS apontado

**Comment by evansantos** [comment]
@anabastos feito o apontamento do CNAME para o github

**Comment by fititnt** [comment]
Algo que a @anabastos ja pode aproveitar e fazer quando for fechar isso aqui é, ali na descrição que aparece no topo da página inicial do github, trocar o link para o novo domínio completo.

**Comment by anabastos** [comment]
@fititnt Tranquilo! Vou fechar a issue já que os links do repositório ja estão ok.
