### ISSUE TITLE
Remover data YYYY-MM-DD para as postagens

### ISSUE THREAD

**Issue by anabastos** [pokemongovet/casos-de-sucesso-na-adocao-de-animais#4]
O @carvalhobruno em https://github.com/pokemongovet/casos-de-sucesso-na-adocao-de-animais/blob/dev/_config.yml#L77 removeu o a data YYYY-MM-DD das urls, porém isso não foi mesclado em produção.

Precisamos disso, e precisamos logo.

@carvalhobruno caso você não consiga fazer isto agora, eu vou pedir pra alguem fazer ok? Esta foi uma otima sugestão.

**Comment by evansantos** [comment]
@anabastos fico responsável por essa em caso o @carvalhobruno não consiga fazer

**Comment by fititnt** [comment]
@evansantos o Carvalho deve tá offline. Se tiver ai pronto pra isso, manda código ou então PR
