### ISSUE TITLE
Link para o chat do grupo no README.md

### ISSUE THREAD

**Issue by fititnt** [pokemongovet/casos-de-sucesso-na-adocao-de-animais#6]
Além do github, também estamos conversando via chat em https://pgovet.rocket.chat/channel/casos-de-sucesso

Alguém pode adicionar um link para o nosso Rocket.chat, preferencialmente com alguma daquelas imagens pequenas? Se a gente não encontrar as imagens, acho que pode ser simplesmente o link mesmo em texto.

**Comment by evansantos** [comment]
Pegando esse =)

**Comment by evansantos** [comment]
Inserido o badge do Rocket.chat no commit https://github.com/pokemongovet/casos-de-sucesso-na-adocao-de-animais/commit/8f36a4d1019249e111a7c91c9b2015f948adda8a

**Comment by evansantos** [comment]
Posso fechar essa issue?

**Comment by fititnt** [comment]
![just do it](https://media.giphy.com/media/wErJXg1tIgHXG/giphy.gif)
